# Generated by Django 6.0.1 on 2026-02-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CasinoFreeBetModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, unique=True)),
                ('tenant_id', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('currency', models.CharField(choices=[('ETB', 'Ethiopian Birr'), ('SZL', 'Swazi Lilangeni'), ('TSh', 'Tanzanian Shilling'), ('ZMW', 'Zambian Kwacha'), ('USD', 'US Dollar')], max_length=5)),
                ('game_id', models.CharField(db_index=True, max_length=100)),
                ('unit_value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('expiry_minutes', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='INACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bonus_casino_freebet',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant_id', 'status'], name='bonus_casin_tenant__fdff21_idx'), models.Index(fields=['created_at', 'expiry_minutes'], name='bonus_casin_created_bc5ad4_idx')],
            },
        ),
    ]
