# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import bonus_pb2 as bonus__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in bonus_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CasinoFreeBetServiceStub(object):
    """Casino Freebet Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateFreebet = channel.unary_unary(
                '/bonus.CasinoFreeBetService/CreateFreebet',
                request_serializer=bonus__pb2.CreateFreebetRequest.SerializeToString,
                response_deserializer=bonus__pb2.FreebetResponse.FromString,
                _registered_method=True)
        self.UpdateStatus = channel.unary_unary(
                '/bonus.CasinoFreeBetService/UpdateStatus',
                request_serializer=bonus__pb2.UpdateStatusRequest.SerializeToString,
                response_deserializer=bonus__pb2.FreebetResponse.FromString,
                _registered_method=True)
        self.GetExpiring = channel.unary_unary(
                '/bonus.CasinoFreeBetService/GetExpiring',
                request_serializer=bonus__pb2.GetExpiringRequest.SerializeToString,
                response_deserializer=bonus__pb2.FreebetListResponse.FromString,
                _registered_method=True)


class CasinoFreeBetServiceServicer(object):
    """Casino Freebet Service
    """

    def CreateFreebet(self, request, context):
        """Create a new casino freebet
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateStatus(self, request, context):
        """Update freebet status (activate/deactivate)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetExpiring(self, request, context):
        """Get freebets expiring soon (for notifications)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CasinoFreeBetServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateFreebet': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateFreebet,
                    request_deserializer=bonus__pb2.CreateFreebetRequest.FromString,
                    response_serializer=bonus__pb2.FreebetResponse.SerializeToString,
            ),
            'UpdateStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateStatus,
                    request_deserializer=bonus__pb2.UpdateStatusRequest.FromString,
                    response_serializer=bonus__pb2.FreebetResponse.SerializeToString,
            ),
            'GetExpiring': grpc.unary_unary_rpc_method_handler(
                    servicer.GetExpiring,
                    request_deserializer=bonus__pb2.GetExpiringRequest.FromString,
                    response_serializer=bonus__pb2.FreebetListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bonus.CasinoFreeBetService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('bonus.CasinoFreeBetService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CasinoFreeBetService(object):
    """Casino Freebet Service
    """

    @staticmethod
    def CreateFreebet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bonus.CasinoFreeBetService/CreateFreebet',
            bonus__pb2.CreateFreebetRequest.SerializeToString,
            bonus__pb2.FreebetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bonus.CasinoFreeBetService/UpdateStatus',
            bonus__pb2.UpdateStatusRequest.SerializeToString,
            bonus__pb2.FreebetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetExpiring(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bonus.CasinoFreeBetService/GetExpiring',
            bonus__pb2.GetExpiringRequest.SerializeToString,
            bonus__pb2.FreebetListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
